[build]
  command = "node scripts/build-for-vercel.js"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8"

# Disable all auto-detection
[build.processing]
  skip_processing = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
